### ISSUE TITLE
Settings for color or custom CSS

### ISSUE THREAD

**Issue by craftedsystems** [sjelfull/craft-entry-instructions#3]
Please add custom CSS option. Thx

**Comment by sjelfull** [comment]
Currently don't have time for this. Open to pull requests, though.

**Comment by adrienne** [comment]
I'm interested in this too; i'll see what i can sort out for a pull request.

**Comment by adrienne** [comment]
@sjelfull - In fact, i just did. 😆 It was pretty easy, it turns out! Pull request submitted, please check it out.

**Comment by sjelfull** [comment]
Thanks, added a new release.

**Comment by adrienne** [comment]
@sjelfull - I just submitted a new pull request because my field instructions weren't clear enough. I also decided i want to be able to override the global CSS settings, rather than just per-field, so I'll probably do that at some point - but i won't have time for a little while, probably, so i'll make another pull request then.
